export type FormulaId = 'basic' | 'square-plus' | 'square-minus' | 'difference-squares';
export type SaltwaterType = 'placement' | 'difference-cross' | 'ratio' | 'mixed-concentration' | 'unknown-amount' | 'add-water' | 'add-salt' | 'evaporation' | 'unknown-concentration' | 'alligation-identify';
export type SequenceType = 'constant-difference'|'constant-ratio'|'growing-difference'|'alternating'|'fibonacci'|'famous-sequence'|'changing-multiplier'|'difference-pattern'|'sequence-identify';
export type LearningStage = 'memorize' | 'forward' | 'reverse' | 'blank' | 'symbol' | 'identify' | 'substitute' | 'compare' | 'place' | 'difference' | 'cross' | 'ratio' | 'apply';
export type SaltwaterData = {
  problemPattern:string; questionIntent:string; lowConcentration:number; targetConcentration:number; highConcentration:number;
  lowAmount?:number; highAmount?:number; leftDifference:number; rightDifference:number; amountRatio:string;
  lowLabel:string; targetLabel:string; highLabel:string; knownWeight?:string; unknownPosition?:string;
  shortRule?:string;
  sourceAmount?:number;
  givenInformation?: { lowConcentration:boolean; targetConcentration:boolean; highConcentration:boolean; lowAmount?:boolean; targetAmount?:boolean; highAmount?:boolean; amountRatio?:boolean; };
  readingClues:string[]; characterTip:string; answerType:'concentration'|'amount'|'ratio'|'identify';
  validationData:{ expected:number; unit:'%'|'g'|'ratio'|'yes-no'; answerText?:string; mix?:{lowAmount:number;highAmount:number}; };
  finalConcentration?:number; diagramMode?:'placement'|'difference'|'cross'|'ratio'|'water'|'salt'|'evaporation';
  hiddenValue?:string; derivationSteps?:string[]; diagramBeforeAnswer?:boolean; diagramAfterAnswer?:boolean;
  mixedConcentration?: { simplifiedAmountRatio:[number,number]; inverseDistanceRatio:[number,number]; totalConcentrationGap:number; gapUnit:number; distanceFromLow:number; distanceFromHigh:number; derivedTargetConcentration:number; };
};
export type SequenceData = { problemPattern:string; sequenceValues:(number|null)[]; blankIndexes:number[]; operationPattern:string[]; differences?:number[]; ratios?:string[]; nextValues:number[]; readingOrder:string; diagramMode:'difference'|'ratio'|'growing-difference'|'alternating'|'fibonacci'|'famous'|'changing-multiplier'|'difference-pattern'|'identify'; validationData:{mode:SequenceType; expectedAnswer:string}; characterTip:string; };
export type Question = { id:string; categoryId:string; subcategoryId:string; typeId:FormulaId|SaltwaterType|SequenceType; difficulty:'basic'; learningStage:LearningStage; question:string; formula:string; choices:string[]; answerIndex:number; shortRule:string; triggerWords:string[]; steps:string[]; explanation:string; deepExplanation:string; mistakeReason:string; diagramType:'sum-product-pair'|'square-tiles'|'difference-squares'|'saltwater-alligation'|'sequence-pattern'; diagramData:Record<string,string>; tags:string[]; saltwater?:SaltwaterData; sequence?:SequenceData };
export type Formula = {id:FormulaId; name:string; formula:string; rule:string; lookFor:string; example:string; diagramType:Question['diagramType']};
